const translation = {
    "master.global.name": "Argentum",
    "master.global.error_connection": "server offline.",
    "master.classes.warrior": "Warrior",
    "master.classes.wizard": "Wizard",
    "master.cities.ullathorpe": "Ullathorpe",
    "master.cities.nix": "Nix",
    "frame.connect.username": "Username",
    "frame.connect.password": "Password",
    "frame.connect.create_button": "Create",
    "frame.connect.enter_button": "Enter",
    "frame.connect.error_empty_fields": "you must complete all the fields to enter your account.",
    "frame.connect.error_characters_username": "username must have a minimum of 4 characters and a maximum of 20.",
    "frame.connect.error_characters_password": "password must have a minimum of 6 characters and a maximum of 18.",
    "frame.connect.error_account_mismatch": "password doesn't match this account.",
    "frame.connect.error_account_unknown": "unknown error, please contact support.",
    "frame.connect.error_account_online": "user is already online.",
    "frame.create_account.title": "Create new account",
    "frame.create_account.username": "Username:",
    "frame.create_account.email": "Email:",
    "frame.create_account.password": "Password:",
    "frame.create_account.repeat_password": "Repeat password:",
    "frame.create_account.tos_one": "I accept the",
    "frame.create_account.tos_two": "of",
    "frame.create_account.tandc": "terms and conditions",
    "frame.create_account.create_button": "Create account",
    "frame.create_account.error_empty_field": "you must complete all the fields and accept the terms and conditions to create an account.",
    "frame.create_account.error_password_not_match": "passwords must match.",
    "frame.create_account.error_invalid_email": "invalid email address, try with a different one.",
    "frame.create_account.error_tos_not_accepted": "you must accept the terms and conditions to create an account.",
    "frame.create_account.error_characters_username": "username must have a minimum of 4 characters and a maximum of 20.",
    "frame.create_account.error_characters_password": "password must have a minimum of 6 characters and a maximum of 18.",
    "frame.create_account.error_account_exist": "this username already exists please use another one.",
    "frame.account.character_list": "Characters list",
    "frame.account.level": "Level",
    "frame.account.delete_character": "Delete character",
    "frame.account.are_you_sure": "Are you sure to delete the character",
    "frame.account.enter_password": "Enter your password to delete your character:",
    "frame.account.confirm_button": "Delete my character",
    "frame.account.enter_character_button": "Enter the game",
    "frame.account.create_new_character_button": "Create new character",
    "frame.account.delete_character_button": "Delete character",
    "frame.account.logout_button": "Log out",
    "frame.account.error_empty_password": "you need to enter your password to delete a character."
}

export default translation;