const translation = {
    "master.global.name": "Argentum",
    "master.global.error_connection": "servidor offline.",
    "master.classes.warrior": "Guerrero",
    "master.classes.wizard": "Mago",
    "master.cities.ullathorpe": "Ullathorpe",
    "master.cities.nix": "Nix",
    "frame.connect.username": "Usuario",
    "frame.connect.password": "Contraseña",
    "frame.connect.create_button": "Crear",
    "frame.connect.enter_button": "Entrar",
    "frame.connect.error_empty_fields": "debes completar todos los campos para ingresar a tu cuenta.",
    "frame.connect.error_characters_username": "el nombre de usuario debe contener un mínimo de 4 caracteres y hasta un máximo de 20.",
    "frame.connect.error_characters_password": "la contraseña debe contener un mínimo de 6 caracteres y hasta un máximo de 18.",
    "frame.connect.error_account_mismatch": "la contraseña no coincide con la de esta cuenta.",
    "frame.connect.error_account_unknown": "error desconocido, póngase en contacto con soporte.",
    "frame.connect.error_account_online": "el usuario ya se encuentra conectado.",
    "frame.create_account.title": "Crear nueva cuenta",
    "frame.create_account.username": "Usuario:",
    "frame.create_account.email": "Email:",
    "frame.create_account.password": "Contraseña:",
    "frame.create_account.repeat_password": "Repetir contraseña:",
    "frame.create_account.tos_one": "Acepto los",
    "frame.create_account.tos_two": "de",
    "frame.create_account.tandc": "términos y condiciones",
    "frame.create_account.create_button": "Crear cuenta",
    "frame.create_account.error_empty_field": "debes completar todos los campos y aceptar los términos y condiciones para crear una cuenta.",
    "frame.create_account.error_password_not_match": "las contraseñas deben coincidir.",
    "frame.create_account.error_invalid_email": "dirección de email inválida, prueba con otra.",
    "frame.create_account.error_tos_not_accepted": "debes aceptar los términos y condiciones para crear una cuenta.",
    "frame.create_account.error_characters_username": "el nombre de usuario debe contener un mínimo de 4 caracteres y hasta un máximo de 20.",
    "frame.create_account.error_characters_password": "la contraseña debe contener un mínimo de 6 caracteres y hasta un máximo de 18.",
    "frame.create_account.error_account_exist": "ya existe un usuario con ese nombre, utiliza otro nombre por favor.",
    "frame.account.character_list": "Lista de personajes",
    "frame.account.level": "Nivel",
    "frame.account.delete_character": "Borrar personaje",
    "frame.account.are_you_sure": "Estás seguro de borrar el personaje",
    "frame.account.enter_password": "Ingresa tu contraseña para borrar el personaje:",
    "frame.account.confirm_button": "Borrar mi personaje",
    "frame.account.enter_character_button": "Ingresar al juego",
    "frame.account.create_new_character_button": "Crear nuevo personaje",
    "frame.account.delete_character_button": "Borrar personaje",
    "frame.account.logout_button": "Cerrar sesión",
    "frame.account.error_empty_password": "debes ingresar tu contraseña para eliminar el personaje."
}

export default translation;