const translation = {
    "global.name": "Argentum",
    "global.error_connection": "servidor offline.",
    "global.level": "Nivel",
    "warrior": "Guerrero",
    "wizard": "Mago",
    "ullathorpe": "Ullathorpe",
    "nix": "Nix",
    "connect.username": "Usuario",
    "connect.password": "Contraseña",
    "connect.create_button": "Crear",
    "connect.enter_button": "Entrar",
    "connect.error_empty_fields": "debes completar todos los campos para ingresar a tu cuenta.",
    "connect.error_characters_username": "el nombre de usuario debe contener un mínimo de 4 caracteres y hasta un máximo de 20.",
    "connect.error_characters_password": "la contraseña debe contener un mínimo de 6 caracteres y hasta un máximo de 18.",
    "connect.error_account_mismatch": "la contraseña no coincide con la de esta cuenta.",
    "connect.error_account_unknown": "error desconocido, póngase en contacto con soporte.",
    "connect.error_account_online": "el usuario ya se encuentra conectado.",
    "create_account.title": "Crear nueva cuenta",
    "create_account.username": "Usuario:",
    "create_account.email": "Email:",
    "create_account.password": "Contraseña:",
    "create_account.repeat_password": "Repetir contraseña:",
    "create_account.tos_one": "Acepto los",
    "create_account.tos_two": "de",
    "create_account.tandc": "términos y condiciones",
    "create_account.create_button": "Crear cuenta",
    "create_account.error_empty_field": "debes completar todos los campos y aceptar los términos y condiciones para crear una cuenta.",
    "create_account.error_password_not_match": "las contraseñas deben coincidir.",
    "create_account.error_invalid_email": "dirección de email inválida, prueba con otra.",
    "create_account.error_tos_not_accepted": "debes aceptar los términos y condiciones para crear una cuenta.",
    "create_account.error_characters_username": "el nombre de usuario debe contener un mínimo de 4 caracteres y hasta un máximo de 20.",
    "create_account.error_characters_password": "la contraseña debe contener un mínimo de 6 caracteres y hasta un máximo de 18.",
    "create_account.error_account_exist": "ya existe un usuario con ese nombre, utiliza otro nombre por favor.",
    "account.character_list": "Lista de personajes",
    "account.delete_character": "Borrar personaje",
    "account.are_you_sure": "Estás seguro de borrar el personaje",
    "account.enter_password": "Ingresa tu contraseña para borrar el personaje:",
    "account.confirm_button": "Borrar mi personaje",
    "account.enter_character_button": "Ingresar al juego",
    "account.create_new_character_button": "Crear nuevo personaje",
    "account.delete_character_button": "Borrar personaje",
    "account.logout_button": "Cerrar sesión",
    "account.error_empty_password": "debes ingresar tu contraseña para eliminar el personaje."
}

export default translation;